### PR TITLE
Create May.md

### PR DESCRIPTION
**Pull request by gcrev93**
Talk submission for May meetup

### CODE REVIEW

**Comment by sixlive** [comment]
This sounds awesome! 

I'll review with @seafoam6 and we'll get things settled!

**Comment by gcrev93** [comment]
Hello TJ

Does this mean I can speak at the May Detroit meetup?

Gabrielle

**Comment by sixlive** [comment]
Yup, you're all set for May!

@seafoam6 and I will get the May event time and date details together later this week!

**Comment by gcrev93** [comment]
awesome thanks :)

**Comment by sixlive** [comment]
No problem! Really looking forward to it

**Comment by sixlive** [comment]
@gcrev93 can you reach out to us at info[at]detroitjs[dot]com to coordinate a few things?

**Comment by gcrev93** [comment]
sent!

**Pull request merged**
